### ISSUE TITLE
Mod breaks bows?

### ISSUE THREAD

**Issue by KaliRanya** [shudnal/HarpoonExtended#1]
I tried out this mod, and found that bow and arrow no longer worked. I could loose an arrow, but it would collide with nothing right in front of my character's face.

Disable the mod, and arrows went back to working OK.

I'll do some more testing to make absolutely sure this is the culprit, but letting you know rn in case you have an idea what might be happening!

**Comment by KaliRanya** [comment]
Yeah, pretty sure I've confirmed it. With no other mods installed than Harpoon Extended, bows become unfireable after using the abyssal harpoon. I gave it a try with and without Better Bows, which does mess with the origin point and firing angle of arrows, but it didn't make a difference.

**Comment by KaliRanya** [comment]
It doesn't seem to be caused by any specific version. I tried all of them back to 1.0.0 and had the same trouble each time.

**Comment by shudnal** [comment]
I have confirmed the issue only for needle and carapace arrows but other arrows seems to work fine. I'm working at solution.
You should test only the current latest 1.1.2 version.

**Comment by KaliRanya** [comment]
oh great! Thanks, I'll use different arrows for now as a workaround.

No worries on the version testing--I was just checking to see if the issue was introduced in a specific version, which might have helped track down the trouble.

**Comment by shudnal** [comment]
Should be fixed in 1.1.4
